### ISSUE TITLE
intersection with cylinder

### ISSUE THREAD

**Issue by Jonas231** [ajhynes7/scikit-spatial#234]
Hi,
great work.
Is it possible to add an object "cylinder" which can be oriented arbitrarily in 3d cartesian space?
Kind regards,
Jonas

**Comment by ajhynes7** [comment]
Hi @Jonas231, thank you!

Sorry I just noticed this issue.

Sure, I think it's possible to add a Cylinder class. It might take me a while though because I'm busy working full time now. Do you want to try making a Pull Request?

**Comment by ajhynes7** [comment]
Just an update - I've started work on this.

**Comment by ajhynes7** [comment]
Hi @Jonas231,

Sorry this took so long. For a while I couldn't find a good method for it, so I left it for a while. But recently I found the equations to intersect a line with an infinite cylinder. This has been merged into master now.
