### ISSUE TITLE
best_fit for sphere object

### ISSUE THREAD

**Issue by martxelo** [ajhynes7/scikit-spatial#241]
Hello.

I think it would be useful to have the same method as the plane object. It would take a set of points and fit them to a sphere with a least squares method. The code is simple and I would like to contribute.

**Comment by ajhynes7** [comment]
Hi @martxelo,

Sure, that sounds good. You can make a Pull Request for it.

**Comment by martxelo** [comment]
Hi @ajhynes7 

It is done!

**Comment by martxelo** [comment]
Hello @ajhynes7 

The PR is done but there is an error in the build. I am not sure what to do because I don't know how to pass the tests.

I did not change the HISTORY.rst because probably this new feature won't be a "new version", and because of that I did not modify the __version__ anywhere, nor the AUTHORS.rst.

Can you help me with this? Maybe you can add or remove something so the code passes the tests. I thought this would be easier...

Regards.

**Comment by ajhynes7** [comment]
@martxelo I'll message you on the PR.

**Comment by ajhynes7** [comment]
This has been merged into master now.
