### ISSUE TITLE
Do you plan to add polyhedron object?

### ISSUE THREAD

**Issue by AlfredQin** [ajhynes7/scikit-spatial#272]
Hello ajhynes7,
Thanks for you amazing work in this repository! Do you plan to add polyhedron geometry in this repository? According to my limit knowledge,  there is no python library that is treating 3D geometry object as convenient as shapely library.

**Comment by ajhynes7** [comment]
Hi @AlfredQin ,

I'm glad you like it!

I think polyhedron would be out of the scope of this library. `scikit-spatial` is mostly about linear algebra concepts, not computational geometry as a whole.

You could check out `scikit-geometry` to see if that meets your needs.
