### ISSUE TITLE
Point - Line Distance Method

### ISSUE THREAD

**Issue by blunovart** [ajhynes7/scikit-spatial#273]
Dear @ajhynes7,
very beautiful library! Simple and very useful!

I am not finding a method for computing the point-line distance. I am a little bit surprised that such a method is not implemented. But for sure I am wrong. 

Thanks!

**Comment by ajhynes7** [comment]
Hi @blunovart , thanks for the kind words!

The point-line distance is in fact implemented. It's a method on the `Line` class called `distance_point`. 

An example usage is here:
https://scikit-spatial.readthedocs.io/en/stable/objects/line.html

But I see that it's missing from the list in the API reference. I'll get that fixed soon. Thanks for pointing it out.

**Comment by blunovart** [comment]
Yeah, I have just noticed that in the documentation of the stable version the method is missing, while in the docs of the latest one is listed:
![image](https://user-images.githubusercontent.com/85804972/126227106-94f625e6-654c-4b0d-a749-018d68eb0f3f.png)

Thank you so much!

**Comment by ajhynes7** [comment]
@blunovart This has been fixed in the new release, v6.1.0.
