### ISSUE TITLE
limit to only 3 points in project_point()

### ISSUE THREAD

**Issue by 3DMiller** [ajhynes7/scikit-spatial#276]
Is there a way to use >3 points for projecting points onto the best fit plane?

**Comment by ajhynes7** [comment]
Hi @3DMiller, the `project_point` method only projects one point at a time. If you want to project many points onto a plane, you can apply the method to each point.

NumPy has a useful function for this: `apply_along_axis`. It will apply `project_point` to each row of the points array. You can wrap this with `Points()` to get a `Points` object.


```python
import numpy as np
from skspatial.objects import Plane

plane = Plane([0, 0, 0], [0, 0, 1])

points = [
    [0, 0, 0],
    [0, 0, 1],
    [0, 1, 0],
    [0, 1, 1],
    [1, 0, 0],
    [1, 0, 1],
    [1, 1, 0],
    [1, 1, 1],
]

points_projected = Points(np.apply_along_axis(plane.project_point, 1, points))

**Comment by 3DMiller** [comment]
And can the plane only be created from 3 points? Can I create a plane with a list of points?

**Comment by ajhynes7** [comment]
You can create a plane from many points by computing the plane of best fit. See [this example from the gallery](https://scikit-spatial.readthedocs.io/en/stable/gallery/fitting/plot_plane.html).

**Comment by 3DMiller** [comment]
Excellent, thanks!

**Comment by Leong1230** [comment]
@ajhynes7 Hi! As for the codes for projecting multiple points to a plane, it is every slow when millions of points are projected.
Do you have any suggestions or faster implementations for projecting so many points at once？
Thank you!

**Comment by ajhynes7** [comment]
@Leong1230 It would be best for you to write the code using NumPy arrays instead of this library. You can look at the code of `Plane.project_point` to see how it works, then modify it so it applies to many points at once instead of one point at a time. This will use NumPy's broadcasting features.

For example, instead of this line (from `Plane.project_point`):

```python
vector_to_plane = Vector.from_points(point, self.point)
```

You would have:

```python
# All of your points go into this array, as the rows.
points = np.array([
    [0, 0, 0]
    [1, 2, 3]
    ...
])

# Define your plane object.
plane = Plane([0, 0, 0], [1, 2, 3])

# This uses broadcasting to subtract `plane.point` from every point in `points`.
vectors_to_plane = points - plane.point
```

**Comment by Leong1230** [comment]
Thank you for reply! The problem is solved now~
