### ISSUE TITLE
ImportError: cannot import name 'Cylinder'

### ISSUE THREAD

**Issue by pauljurczak** [ajhynes7/scikit-spatial#278]
I just installed `scikit-spatial` with `pip3` on Ubuntu 18.04 and Python 3.6.9. A simple example with points works, but:
```
>>> from skspatial.objects import Cylinder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Cylinder'
```

**Comment by ajhynes7** [comment]
Hi Paul, could you check which version of `scikit-spatial` was installed?

```sh
$ pip3 show scikit-spatial
```

**Comment by pauljurczak** [comment]
```
paul@desktop:~$ pip3 show scikit-spatial
Name: scikit-spatial
Version: 5.2.0
```

**Comment by pauljurczak** [comment]
I see that this is an old version. I will look into getting a newer one.

**Comment by ajhynes7** [comment]
Sure, you can try running this:

```sh
$ pip3 install -U scikit-spatial
```

Hopefully that'll install the latest version (6.1.0) for you.

**Comment by pauljurczak** [comment]
It doesn't, but it is to be expected. Ubuntu 18.04 is far behind the newest versions of C/C++ library dependencies. Not a problem, I will be upgrading the OS.
