### ISSUE TITLE
plot_3d doesn't work. Am I missing dependencies?

### ISSUE THREAD

**Issue by pauljurczak** [ajhynes7/scikit-spatial#282]
I have `scikit-spatial 6.1.0` and Python 3.8.10 un Ubuntu 20.04.3 MATE. Basic examples work, `matplotlib` works, but `plot_3d` fails to produce anything. I was trying this example: https://scikit-spatial.readthedocs.io/en/stable/gallery/projection/plot_vector_line.html

**Comment by ajhynes7** [comment]
How are you running this code? In JupyterLab or another way?

**Comment by pauljurczak** [comment]
From command line. Specifically, VS Code terminal window.

**Comment by ajhynes7** [comment]
Try adding this to your script:

```python
import matplotlib.pyplot as plt

# All of your code

plt.show()
```

**Comment by pauljurczak** [comment]
Thank you. That's what was missing. I wasn't aware that `matplotlib` is used in the background.
