### ISSUE TITLE
Why use importlib-metadata version 1.x?

### ISSUE THREAD

**Issue by kye9216789** [ajhynes7/scikit-spatial#290]
When I want to use scikit-spatial with other packages, it conflicts by importlib-metadata.
Latest version of importlib-metadata is 4.x but scikit-spatial foces 1.x.
Other packages usually force importlib-metadata version over 3.x

**Comment by ajhynes7** [comment]
Hi RaramRa,

I've released a new version of scikit-spatial, v6.2.1, which should fix your problem. If you confirm that it does, I can close this issue.

**Comment by kye9216789** [comment]
I want importlib-metadata installed 3.8, but when I run pip install scikit-spatial==6.2.1, importlib-metadata==1.7.0 is installed

**Comment by ajhynes7** [comment]
You shouldn't use the installation of scikit-spatial to get your desired version of importlib-metadata. If you want a specific version of importlib-metadata, you can install it with pip. 

scikit-spatial just specifies the minimum allowed version of importlib-metadata.

Try running this:

```sh
$ pip install scikit-spatial importlib-metadata==3.8
```
