### ISSUE TITLE
[enhancement] Projection of a line onto a plane.

### ISSUE THREAD

**Issue by CristianoPizzamiglio** [ajhynes7/scikit-spatial#299]
Hi! I hope everything's fine!

I was wondering the following, but let me know if it makes sense to you or not, please. Thanks!

The `Plane` object already has the `project_vector` method. However, very often I need the projected line (and not only its vector) because I need to use the specific `Line`'s methods.

Would it make sense to you to add a `project_line` method to the `Plane` object? I was thinking to write something similar to the following (I have omitted both documentation and error handling, now I just want to give you an idea):

```Python
def project_line(plane: Plane, line: Line) -> Line:
    direction = plane.project_vector(line.direction)
    point = plane.project_point(line.point)
    return Line(point=point, direction=direction)
```

Bye!

**Comment by ajhynes7** [comment]
Hi Christiano,

Everything's fine, thanks!

I remember considering this before, but I didn't bother because as you said it's similar to projecting a vector onto the plane. But I'm fine with adding it to the package if you'd like to make a PR for it.

**Comment by blunovart** [comment]
Good! I am going to open a PR in the next days, thanks!

**Comment by CristianoPizzamiglio** [comment]
Good! I am going to open a PR in the next days, thanks!
