### ISSUE TITLE
Mesh for cylinders has wrong radius if not axis-aligned.

### ISSUE THREAD

**Issue by luzader** [ajhynes7/scikit-spatial#306]
Hello. Great work with this library. Unfortunately I did find an issue where the mesh generated for cylinders only has the correct radius if the cylinder's vector is axis-aligned. For cylinders with arbitrary vectors the radius is smaller than requested. You can see this with the following minimal example:

```
from matplotlib import pyplot as plt
from skspatial.objects import Cylinder, Sphere

fig = plt.figure()
ax = fig.add_subplot(111, projection="3d")

center = [0, 0, 0]
ax.plot_wireframe(*Sphere(center, 1).to_mesh())
ax.plot_wireframe(*Cylinder(center, [1, 0, 0], 1).to_mesh(4, 32), color='g')
ax.plot_wireframe(*Cylinder(center, [0.707, .707, 0], 1).to_mesh(4, 32), color='r')

ax.set_xlim((-3, 3))
ax.set_ylim((-3, 3))
ax.set_zlim((-3, 3))
plt.tight_layout()
plt.show()
```

The green cylinder has the correct radius, matching the blue sphere, but the red cylinder is too small by a factor of 0.707.

![SkSpatialCylinderProblem](https://user-images.githubusercontent.com/617962/173115392-81253d91-f716-45af-ae8f-68d6593c731a.png)

**Comment by ajhynes7** [comment]
Hi @luzader, thanks for catching this.

I have a PR up now to fix it.

**Comment by ajhynes7** [comment]
Hi @luzader, I've released a new version with the fix.
