### ISSUE TITLE
python3.6.x

### ISSUE THREAD

**Issue by blairstar** [ajhynes7/scikit-spatial#316]
hello, thanks for your great job.
have any way to use scikit-spatial with python3.6.x?

**Comment by ajhynes7** [comment]
Thanks @blairstar, but I would say no to your question because this package depends on `numpy` and `matplotlib`, and they've deprecated support for Python 3.6. 

Python 3.6 is already past its end of life.
https://endoflife.date/python

**Comment by dancergraham** [comment]
Hello, arriving very late to this one but in case anyone else is interested version 3.0.0 of scikit spatial was listed as compatible with python 3.6 https://pypi.org/project/scikit-spatial/3.0.0/#files
