### ISSUE TITLE
intersection line are not complanar with line in plane

### ISSUE THREAD

**Issue by volkoshkursk** [ajhynes7/scikit-spatial#319]
Hello! I generate a plane from points and make a plane from point and normal. Then I make an intersection line with ```Plane.intersect_plane```. When I try to find an intersection point of the intersection line and a line from points, which was used to making a first plane I get an error

```    563     raise ValueError("The lines must not be parallel.")
    565 if not self.is_coplanar(other, tol=tol):
--> 566     raise ValueError("The lines must be coplanar.")
    568 # Vector from line A to line B.
    569 vector_ab = Vector.from_points(self.point, other.point)

ValueError: The lines must be coplanar.
```

**Comment by ajhynes7** [comment]
Hello @volkoshkursk,

Could you please post a minimal working example of this? I'll need to see this in code to decide if this is an issue.

**Comment by ajhynes7** [comment]
It doesn't make sense to add a tolerance to the coplanar check in `Line.intersect_line`. If the lines are not coplanar, then they cannot have an intersection point.

**Comment by volkoshkursk** [comment]
These lines can not be non-coplanar due to the fact that ```line``` is build with the points, which was the plane build with and  ```secant``` is intersection of the plane and another plane. If we check distance between one of the point from ```points``` and ```plane```  with ```Plane.distance_point``` it would not be 0, which would be impossible if we had precise data. The error is happens because we check the coplanarity with more precision that is in data.  This situation is equal to ```is_parallel```'s limitation of tolerance. My hypothesis also can be proofed graphically.

**Comment by ajhynes7** [comment]
> This situation is equal to is_parallel's limitation of tolerance.

It's actually not the same. See this code:

```python

        if self.direction.is_parallel(other.direction, **kwargs):
            raise ValueError("The lines must not be parallel.")

        if not self.is_coplanar(other):
            raise ValueError("The lines must be coplanar.")
```

Notice that the first check is "if parallel", but the second check is "if NOT coplanar". So passing a tolerance to `is_parallel` makes that check more strict, but passing a tolerance to `is_coplanar` would make the check less strict. 

If the lines aren't coplanar, then the output of this method will not be an intersection point of the two lines. It'll be the point on line A which is closest to line B, but it won't be an actual intersection point because the lines don't intersect.

I tried your code without the `is_coplanar` check, and the resulting point is indeed not on line B, which I verified by running this:

```python
>>> point = line.intersect_line(intersection)

>>> intersection.contains_point(point)
False
```

**Comment by volkoshkursk** [comment]
However, if we calculate the distance between the point and line we get the value, which is less than data precision.

```
>>> intersection.distance_point(point)
2.9251899693564517e-06
```
I completely agree, that it would be non-coplanar if the data was enought precise. However, my data's precision is limited by accuracy of sensor. So, difference less then 10^-6 in absolute value is most probably  due to inaccuracy of collecting/storage/processing data.

**Comment by ajhynes7** [comment]
Ok, how about I add a keyword argument `check_coplanar` with default value `True`? Then you can disable the coplanar check when needed by passing `check_coplanar=False`.

**Comment by ajhynes7** [comment]
Then I think we should have two types of kwargs in the function signature: `is_parallel_kwargs` and `is_coplanar_kwargs`.

**Comment by volkoshkursk** [comment]
Yes, you are right. I solve this by adding an optional parameter ```tol``` to ```Plane.intersect_line```. Also, it was necessary to add this parameter as optional to functions, which depend on  ```Line.intersect_line```. More detailed description I add as comment to pull request.

In general, ```numpy.linalg.optional```, witch is called from ```is_coplanar```, has only 2 optional parameters: ```tol=None``` and ```hermitian=False```.  However, I did't face wis situation when I need to change ```hermitian=False``` in context of this task.

**Comment by ajhynes7** [comment]
Would you be fine for me to do this myself, or would you rather I review your PR?

**Comment by volkoshkursk** [comment]
I would like you to review my PR

**Comment by dancergraham** [comment]
Hello I think you have some trailing whitespaces causing the automatic checks to fail. 
```
trim trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing src/skspatial/objects/line.py
Fixing src/skspatial/objects/line_segment.py
```
