### ISSUE TITLE
Intersection between 2 Circles

### ISSUE THREAD

**Issue by typhoon71** [ajhynes7/scikit-spatial#323]
Hi,

I'd like to ask if you could add intersectionn check between circles.

Right now it's possible to find intersection point between two lines, or between a line and a circle, but not between two circles.

Would it be possible? Thanks anyway.

I find scikit-spatial a useful tool for me, so thanks for it.

**Comment by ajhynes7** [comment]
Hi @typhoon71,

Sure, that sounds doable. I'll work on this soon.

**Comment by typhoon71** [comment]
Terrific, thank you very much.

**Comment by ajhynes7** [comment]
@typhoon71 FYI, I just released version `6.7.0` which includes this feature.

**Comment by typhoon71** [comment]
That was fast! Thank you very much.

**Comment by ajhynes7** [comment]
You're welcome! Haha I won't always be that fast - I just had some free time this week.
