### ISSUE TITLE
Why raising ValueError instead of returning an empty list?

### ISSUE THREAD

**Issue by typhoon71** [ajhynes7/scikit-spatial#325]
Hi,

I was wondering why you choose to raise a ValueError when the .intersect_line() or .intersect_circle(), well, don't have intersecting points.

I'm curious if there is any particular reason, as far I remember 0 points of intersection is still "correct" (no intersections). so I'd expect an empty list to be returned instead.

I can work around this, but I'm curious about why it behaves like this.

**Comment by ajhynes7** [comment]
It's the pattern I've used for all the intersection methods. A `ValueError` is raised if there is no real intersection.

If you want empty lists instead, you can easily get them by wrapping the call in a try/except block. For example:

```python
try:
    point_a, point_b = circle_a.intersect_circle(circle_b)

except ValueError:
    point_a, point_b = [], []
```

**Comment by ajhynes7** [comment]
By raising a `ValueError`, I'm giving the user the flexibility to handle the error in the way that they want. You could assign `point_a` and `point_b` to `None` instead, if you want.

**Comment by typhoon71** [comment]
Ok, I understand now your reason, thank you.
