### ISSUE TITLE
AttributeError: 'LineSegment' object has no attribute 'plotter'

### ISSUE THREAD

**Issue by Yeok-c** [ajhynes7/scikit-spatial#335]
LineSegment class can't plot in 2D nor in 3D. You can verify this as simple as:

`linesegment = LineSegment(Point([0, 1, 1]),Point([0, 2, 2]))

plot_3d(
    linesegment.plotter()
)

Output:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[95], line 4
      1 linesegment = LineSegment(Point([0, 1]),Point([0, 2]))
      3 plot_3d(
----> 4     linesegment.plotter()
      5 )

AttributeError: 'LineSegment' object has no attribute 'plotter'`

**Comment by CristianoPizzamiglio** [comment]
Hi @Yeok-c!
Try to read the [documentation ](https://scikit-spatial.readthedocs.io/en/stable/api_reference/skspatial.objects.LineSegment.html)more carefully. The methods you are looking for are [`plot_2d` ](https://scikit-spatial.readthedocs.io/en/stable/api_reference/LineSegment/methods/skspatial.objects.LineSegment.plot_2d.html#skspatial.objects.LineSegment.plot_2d)and [`plot_3d`](https://scikit-spatial.readthedocs.io/en/stable/api_reference/LineSegment/methods/skspatial.objects.LineSegment.plot_3d.html#skspatial.objects.LineSegment.plot_3d).

Thanks.

**Comment by ajhynes7** [comment]
Hmm actually @Yeok-c has a point. The `LineSegment` class is missing the `plotter` method.

The fix is pretty easy. I'll get to it soon.

**Comment by CristianoPizzamiglio** [comment]
Sorry, I apologize! Thanks for letting me know!
