### ISSUE TITLE
`Ellipse`/`Ellipsoid` classes

### ISSUE THREAD

**Issue by CristianoPizzamiglio** [ajhynes7/scikit-spatial#339]
Hi!

This is not an issue, but just a discussion.

Have you ever thought about adding `Ellipsoid` and `Ellipse` classes? Similar to the `Sphere`/`Circle` classes, we could create a `_BaseEllipsoid` class which is inherited by both `Ellipsoid` and `Ellipse` classes. I am glad to help if you consider this valuable.

By the way, what about adding the `Discussions` tab for this library? Maybe it's too early?

Thanks!

**Comment by ajhynes7** [comment]
Hi, I'm on vacation so I may not respond for the next two weeks. 
\\
his sounds like it could fit with the library so feel free to make a PR.
