### ISSUE TITLE
Plane from normal vector and point.

### ISSUE THREAD

**Issue by MikiGrit** [ajhynes7/scikit-spatial#340]
Hi, I'm working with planes and I would like to know what is the best way with skspatial library to compute Plane object from normal vector and plane.

Thanks.

**Comment by ajhynes7** [comment]
Hi @MikiGrit,

I'm not sure what this means. You already have a plane, and you want to compute another plane?

**Comment by MikiGrit** [comment]
Hi, sorry for the confusing description. I have a vector and a point. And I want to use those to construct skspatial Plane object. Vector represents normal vector for that plane and point should lie on the same plane. And I'm not sure what is the best approach.

I can compute plane equation (i.e. "ax + by + cz - d = 0") but to construct Plane from it one has to check for various boundary conditions and deal with them. So I'm wondering if there is a better way?

Thanks.

**Comment by CristianoPizzamiglio** [comment]
Hi @MikiGrit!

You can create the plane as follows:

```python
plane = Plane(point=[0, 0, 0], normal=[0, 0, 23])
```
you just need to replace the lists with the point and vector that you already have.

For further details, take a look [here](https://scikit-spatial.readthedocs.io/en/stable/objects/plane.html), thanks.

**Comment by MikiGrit** [comment]
Oh, thank you @CristianoPizzamiglio! I missed that part in the documentation.
