### ISSUE TITLE
Document opperators

### ISSUE THREAD

**Issue by garyvdm** [ajhynes7/scikit-spatial#354]
Took me quite a bit of time to realize I can do `Point + Vector`.  I think I have looked at all the documentations, but could not find anything that mentions this.

I think it would be helpful if the various operators that are supported are documented.

**Comment by ajhynes7** [comment]
From the README:

>The primary objects of scikit-spatial (Point, Points, and Vector) are actually subclasses of the NumPy ndarray. This gives them all the regular functionality of the ndarray, plus additional methods from this package.

So you can add them together like regular NumPy arrays.

But you're right that there's no example for adding a `Point` and a `Vector`. I can add one to the README, and to the [Point and Vector](https://scikit-spatial.readthedocs.io/en/stable/objects/point_vector.html) page of the docs.
