### ISSUE TITLE
Any plans to support numpy>=2.1 ?

### ISSUE THREAD

**Issue by manuel-koch** [ajhynes7/scikit-spatial#357]
We like to upgrade our usage of `numpy` to the latest possible version >=2.1, but `scikit-spatial` explicitly rejects numpy>=2 in its dependency configuration, see `pyproject.toml`.

Are there any plans to support `numpy>=2.1` too ?

**Comment by ajhynes7** [comment]
I'll start working on this.

**Comment by ajhynes7** [comment]
The new release (8.0.0) supports NumPy 2.
